### PR TITLE
Fix new feeds spamming the channel

### PR DESCRIPTION
**Pull request by frezbo**
Signed-off-by: Noel Georgi <git@frezbo.com>

Fixes https://github.com/wbernest/mattermost-plugin-rssfeed/issues/20

When subscribing to a new feed, only post the latest feed. This is similar to the behavior as seen in the slack RSS feed plugin. For new subscriptions only posts the newest one in the feed.

### CODE REVIEW

**Comment by frezbo** [comment]
image
This is the new behavior. Previously subscribing the AWS RSS feed would have created a message flood.

**Comment by bbodenmiller** [comment]
@wbernest any chance you can review the recent MRs and cut a release?

**Comment by wbernest** [comment]
@bbodenmiller done.

**Comment by bbodenmiller** [comment]
@wbernest thanks. Is it possible something went wrong with release? I'm seeing the new options added in https://github.com/wbernest/mattermost-plugin-rssfeed/pull/40 but the functionality of this PR, https://github.com/wbernest/mattermost-plugin-rssfeed/pull/40, & https://github.com/wbernest/mattermost-plugin-rssfeed/pull/42 appears to be working as it was before update.

**Comment by wbernest** [comment]
@bbodenmiller I did pull in a couple of outstanding pull requests and had a little merge, but it was in the package.json and an import statement, so that shouldn't have affected anything.

**Comment by frezbo** [comment]
@wbernest  is this because the version was not bumped in `plugin.json`?

**Pull request merged**
